name: activity_tracker
description: "Activity tracker app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  get:
  firebase_core:
  firebase_auth:
  cloud_firestore:

flutter:
  uses-material-design: true
